do not build description files
This lead to error TS4023 when a type if needed to describe something
that has not been imported to the module. See also
https://github.com/Microsoft/TypeScript/issues/5711#issuecomment-157793294